Minor edits to AchievementCredential/OpenBadgeCredential
IMSGlobal/openbadges-specification pull request #407
Opened 2022-05-11 20:06 UTC by kayaelle

2022-05-11 23:05 UTC, amiller-ims requested changes

2022-05-11 23:05 UTC, amiller-ims commented on ob_v3p0/common_credentials.lines
> -    Class AchievementCredential Unordered false [VerifiableCredential] "AchievementCredentials are representations of an awarded achievement, used to share information about a achievement belonging t
The class name `AchievemementCredential` was approved by the project group in PR #403.

2022-05-12 12:11 UTC, kayaelle commented
Isn't AchievementCredential an alias of OpenBadgeCredential? In the context of Open Badges, can we refer to it as an OpenBadgeCredential with a reference to the alias vs the other way around?

2022-05-12 15:33 UTC, justinpitcher commented
Going to reject PR. As discussed, adjust description to make aliasing more explicit and move context changes to a different PR/branch WIP.

2022-05-12 15:33 UTC, closed without merging